'use strict';

const t = window.I18N.t;

// ---------- State ----------
const state = {
  drives: [],
  scans: {},            // saved-scans index (from list-scans)
  navStack: [],         // node path from root to current node
  scanRoot: null,       // root of the current scan (the drive)
  driveId: null,
  displayName: '',
  prevRoot: null,       // previous scan for comparison
  prevMeta: null,
  viewMode: 'browse',   // browse | biggest | changes
  sortMode: 'size-desc',
  thresholdGB: 40,
  minSizeGB: 0,
  scanning: false,
  hasResults: false,
  lastResultRoot: null
};

const GB = 1024 ** 3;

// ---------- Elements ----------
const el = {
  viewHome: document.getElementById('view-home'),
  viewScanning: document.getElementById('view-scanning'),
  viewResults: document.getElementById('view-results'),
  drivesList: document.getElementById('drives-list'),
  btnHome: document.getElementById('btn-home'),
  btnBackResults: document.getElementById('btn-back-results'),
  btnRefresh: document.getElementById('btn-refresh-drives'),
  btnCancelScan: document.getElementById('btn-cancel-scan'),
  langToggle: document.getElementById('lang-toggle'),
  scanTitle: document.getElementById('scan-title'),
  scanCount: document.getElementById('scan-count'),
  scanPath: document.getElementById('scan-path'),
  tabs: Array.from(document.querySelectorAll('.tab')),
  tabChanges: document.getElementById('tab-changes'),
  scanMeta: document.getElementById('scan-meta'),
  modeBrowse: document.getElementById('mode-browse'),
  modeFlat: document.getElementById('mode-flat'),
  breadcrumb: document.getElementById('breadcrumb'),
  currentName: document.getElementById('current-name'),
  currentSize: document.getElementById('current-size'),
  sortSelect: document.getElementById('sort-select'),
  minsizeSlider: document.getElementById('minsize-slider'),
  minsizeValue: document.getElementById('minsize-value'),
  thresholdSlider: document.getElementById('threshold-slider'),
  thresholdValue: document.getElementById('threshold-value'),
  treemap: document.getElementById('treemap'),
  itemsList: document.getElementById('items-list'),
  versionPill: document.getElementById('version-pill'),
  updateBanner: document.getElementById('update-banner'),
  updateText: document.getElementById('update-text'),
  updateAction: document.getElementById('update-action'),
  updateDismiss: document.getElementById('update-dismiss'),
  aboutModal: document.getElementById('about-modal'),
  aboutClose: document.getElementById('about-close'),
  aboutCurrentVersion: document.getElementById('about-current-version'),
  aboutCheck: document.getElementById('about-check'),
  aboutUpdateStatus: document.getElementById('about-update-status'),
  whatsnewList: document.getElementById('whatsnew-list'),
  flatTitle: document.getElementById('flat-title'),
  flatHint: document.getElementById('flat-hint'),
  flatListHead: document.getElementById('flat-list-head'),
  flatList: document.getElementById('flat-list'),
  toast: document.getElementById('toast'),
  volumeStrip: document.getElementById('volume-strip'),
  vsName: document.getElementById('vs-name'),
  vsUsed: document.getElementById('vs-used'),
  vsFree: document.getElementById('vs-free'),
  vsFill: document.getElementById('vs-fill'),
  vsPct: document.getElementById('vs-pct')
};

// ---------- Utils ----------
function formatSize(bytes) {
  bytes = Number(bytes) || 0;
  const TB = 1024 ** 4, MB = 1024 ** 2, KB = 1024;
  if (bytes >= TB) return (bytes / TB).toFixed(2) + ' TB';
  if (bytes >= GB) return (bytes / GB).toFixed(2) + ' GB';
  if (bytes >= MB) return (bytes / MB).toFixed(1) + ' MB';
  if (bytes >= KB) return (bytes / KB).toFixed(0) + ' KB';
  return bytes + ' B';
}
function thresholdBytes() { return state.thresholdGB * GB; }
function sanitizeId(id) { return String(id).replace(/[^A-Za-z0-9]/g, '') || 'x'; }
function fmtInt(n) { return Number(n).toLocaleString(window.I18N.locale()); }

// Localized display name for tree nodes whose names are generated by the scanner.
function dispName(n) {
  if (!n) return '';
  if (n.type === 'files-here') return t('filesHere');
  if (n.type === 'more-bucket') {
    const count = (typeof n.itemCount === 'number') ? n.itemCount : null;
    if (count !== null) return t('moreItems', { n: fmtInt(count) });
  }
  return n.name;
}

// Virtual "all drives" root has no path and no driveId.
function isVirtualRoot(n) { return n && !n.driveId && !n.path && Array.isArray(n.children); }
function rootLabel(n) {
  if (isVirtualRoot(n)) return t('allDrives');
  return n.displayName || n.name;
}

function driveTypeName(driveType) {
  switch (Number(driveType)) {
    case 2: return t('typeRemovable');
    case 3: return t('typeFixed');
    case 4: return t('typeNetwork');
    case 5: return t('typeCD');
    default: return t('typeOther');
  }
}

function relativeTime(iso) {
  if (!iso) return '';
  const then = new Date(iso).getTime();
  const s = Math.max(0, (Date.now() - then) / 1000);
  if (s < 60) return t('justNow');
  const m = Math.floor(s / 60); if (m < 60) return t('minAgo', { n: m });
  const h = Math.floor(m / 60); if (h < 24) return t('hrAgo', { n: h });
  const d = Math.floor(h / 24); if (d === 1) return t('yesterday');
  if (d < 30) return t('daysAgo', { n: d });
  const mo = Math.floor(d / 30); if (mo < 12) return t('moAgo', { n: mo });
  return t('overYear');
}

function showView(name) {
  el.viewHome.hidden = name !== 'home';
  el.viewScanning.hidden = name !== 'scanning';
  el.viewResults.hidden = name !== 'results';
  el.btnHome.hidden = name === 'home';
  el.btnBackResults.hidden = !(name === 'home' && state.hasResults);
}

let toastTimer = null;
function toast(msg) {
  el.toast.textContent = msg;
  el.toast.hidden = false;
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => { el.toast.hidden = true; }, 2600);
}

// ---------- Drives (home) ----------
async function loadDrives() {
  // Placeholder only when the cache is empty - avoids flicker on refresh
  if (!state.drives.length) {
    el.drivesList.innerHTML = '<div class="empty-state">' + t('loadingDrives') + '</div>';
  }
  const [drives, scans] = await Promise.all([window.api.listDrives(), window.api.listScans()]);
  state.drives = drives;
  state.scans = scans || {};
  renderDrives();
  renderVolumeStrip(); // keep the results-view strip in sync with fresh free-space data
}

// Back to home with refreshed drives + scan status (and updated free space)
function goHome() {
  showView('home');
  loadDrives();
}

function renderDrives() {
  el.drivesList.innerHTML = '';
  if (!state.drives.length) {
    el.drivesList.innerHTML = '<div class="empty-state">' + t('noDrives') + '</div>';
    return;
  }

  const fixed = state.drives.filter((d) => d.driveType === 3);
  if (fixed.length > 1) {
    const allCard = document.createElement('div');
    allCard.className = 'drive-card';
    const topAll = document.createElement('div');
    topAll.className = 'drive-top';
    const nameAll = document.createElement('span');
    nameAll.className = 'drive-name';
    nameAll.textContent = '🖥️ ' + t('allDrives');
    topAll.appendChild(nameAll);
    const descAll = document.createElement('div');
    descAll.className = 'drive-label';
    descAll.textContent = t('scanAllDesc');
    allCard.appendChild(topAll);
    allCard.appendChild(descAll);
    const btn = document.createElement('button');
    btn.className = 'btn btn-primary';
    btn.textContent = t('scanAllBtn');
    btn.addEventListener('click', () => scanAll(fixed));
    allCard.appendChild(btn);
    el.drivesList.appendChild(allCard);
  }

  state.drives.forEach((d) => {
    const pct = d.total > 0 ? (d.used / d.total) * 100 : 0;
    const fillClass = pct >= 90 ? 'full' : pct >= 75 ? 'warn' : '';
    const scan = state.scans[sanitizeId(d.id)];

    const card = document.createElement('div');
    card.className = 'drive-card';

    const top = document.createElement('div');
    top.className = 'drive-top';
    const dname = document.createElement('span');
    dname.className = 'drive-name';
    dname.textContent = '💽 ' + d.id;
    const dtype = document.createElement('span');
    dtype.className = 'drive-type';
    dtype.textContent = driveTypeName(d.driveType);
    top.appendChild(dname);
    top.appendChild(dtype);

    const label = document.createElement('div');
    label.className = 'drive-label';
    label.textContent = d.label ? d.label : t('noLabel');

    const bar = document.createElement('div');
    bar.className = 'drive-bar';
    bar.innerHTML = '<div class="drive-bar-fill ' + fillClass +
      '" style="width:' + pct.toFixed(1) + '%"></div>';

    const stats = document.createElement('div');
    stats.className = 'drive-stats';
    const usedSpan = document.createElement('span');
    usedSpan.className = 'used-txt';
    usedSpan.textContent = t('usedOf', { used: formatSize(d.used), pct: pct.toFixed(0) });
    const freeSpan = document.createElement('span');
    freeSpan.textContent = t('freeAmt', { free: formatSize(d.free) });
    stats.appendChild(usedSpan);
    stats.appendChild(freeSpan);

    const lastscan = document.createElement('div');
    if (scan) {
      lastscan.className = 'drive-lastscan';
      lastscan.textContent = t('scannedAgo', { when: relativeTime(scan.scannedAt), size: formatSize(scan.totalSize) });
    } else {
      lastscan.className = 'drive-lastscan none';
      lastscan.textContent = t('notScanned');
    }

    const btns = document.createElement('div');
    btns.className = 'drive-btns';
    if (scan) {
      const showBtn = document.createElement('button');
      showBtn.className = 'btn btn-ghost';
      showBtn.textContent = t('showLast');
      showBtn.addEventListener('click', () => showCached(d.id));
      const rescanBtn = document.createElement('button');
      rescanBtn.className = 'btn btn-primary';
      rescanBtn.textContent = t('rescan');
      rescanBtn.addEventListener('click', () => scanSingle(d));
      btns.appendChild(showBtn);
      btns.appendChild(rescanBtn);
    } else {
      const scanBtn = document.createElement('button');
      scanBtn.className = 'btn btn-primary';
      scanBtn.textContent = t('scanThis');
      scanBtn.addEventListener('click', () => scanSingle(d));
      btns.appendChild(scanBtn);
    }

    card.appendChild(top);
    card.appendChild(label);
    card.appendChild(bar);
    card.appendChild(stats);
    card.appendChild(lastscan);
    card.appendChild(btns);
    el.drivesList.appendChild(card);
  });
}

// ---------- Volume usage strip (results view) ----------
// Shows total capacity / used / free of the volume being browsed - visible in
// every results mode and at every depth, not only on the home screen.
function computeVolInfo() {
  const root = state.scanRoot;
  if (!root) return null;
  if (isVirtualRoot(root)) {
    const fixed = state.drives.filter((d) => d.driveType === 3);
    if (!fixed.length) return null;
    let total = 0, free = 0;
    for (const d of fixed) { total += d.total; free += d.free; }
    return { label: t('allDrives'), total, free, used: total - free };
  }
  if (root.driveId) {
    const d = state.drives.find((x) => x.id === root.driveId);
    if (d && d.total > 0) {
      return { label: rootLabel(root), total: d.total, free: d.free, used: d.used };
    }
  }
  return null;
}

function renderVolumeStrip() {
  if (!el.volumeStrip) return;
  const info = computeVolInfo();
  if (!info) { el.volumeStrip.hidden = true; return; }
  const pct = info.total > 0 ? (info.used / info.total) * 100 : 0;
  el.vsName.textContent = '💽 ' + info.label;
  el.vsUsed.textContent = t('volUsed', { used: formatSize(info.used), total: formatSize(info.total) });
  el.vsFree.textContent = t('volFree', { free: formatSize(info.free) });
  el.vsFill.style.width = pct.toFixed(1) + '%';
  el.vsFill.className = 'vs-fill ' + (pct >= 90 ? 'full' : pct >= 75 ? 'warn' : '');
  el.vsPct.textContent = pct.toFixed(0) + '%';
  el.volumeStrip.hidden = false;
}

// ---------- Scanning ----------
function startScanningUI(title) {
  state.scanning = true;
  el.scanTitle.textContent = title;
  el.scanCount.textContent = t('filesScanned', { n: fmtInt(0) });
  el.scanPath.textContent = '';
  showView('scanning');
}

async function scanSingle(drive) {
  startScanningUI(t('scanningX', { x: drive.id }));
  const res = await window.api.scanStart(drive.path);
  if (!state.scanning) return; // cancelled
  state.scanning = false;
  if (!res.ok) {
    toast(t('scanFailedErr', { err: res.error || '' }));
    showView('home');
    return;
  }
  const tree = res.tree;
  tree.driveId = drive.id;
  tree.displayName = drive.id + (drive.label ? ' (' + drive.label + ')' : '');
  tree.scannedAt = new Date().toISOString();
  await openTree(tree, { save: true });
}

async function scanAll(fixedDrives) {
  startScanningUI(t('scanningAll'));
  const roots = [];
  let totalSize = 0;
  for (const d of fixedDrives) {
    if (!state.scanning) return;
    el.scanTitle.textContent = t('scanningX', { x: d.id });
    const res = await window.api.scanStart(d.path);
    if (!state.scanning) return;
    if (res.ok && res.tree) {
      const dn = d.id + (d.label ? ' (' + d.label + ')' : '');
      res.tree.displayName = dn;
      res.tree.name = d.id + '\\';
      res.tree.driveId = d.id;
      const scannedAt = new Date().toISOString();
      res.tree.scannedAt = scannedAt;
      await window.api.saveScan({
        driveId: d.id, displayName: dn, rootPath: d.path,
        totalSize: res.tree.size, scannedAt, tree: res.tree
      });
      roots.push(res.tree);
      totalSize += res.tree.size;
    }
  }
  state.scanning = false;
  state.scans = await window.api.listScans();
  if (!roots.length) {
    toast(t('scanFailed'));
    showView('home');
    return;
  }
  const virtualRoot = {
    name: t('allDrives'), displayName: t('allDrives'), path: null,
    size: totalSize, type: 'dir', children: roots
  };
  await openTree(virtualRoot, { save: false });
}

async function showCached(driveId) {
  const res = await window.api.loadScan(driveId);
  if (!res.ok) { toast(t('noSavedScan')); return; }
  const tree = res.tree;
  tree.driveId = res.meta.driveId;
  tree.displayName = res.meta.displayName || tree.name;
  tree.scannedAt = res.meta.scannedAt;
  await openTree(tree, { save: false });
}

async function cancelScan() {
  state.scanning = false;
  await window.api.scanCancel();
  goHome();
}

// ---------- Open results ----------
async function openTree(root, opts) {
  opts = opts || {};
  state.navStack = [root];
  state.scanRoot = root;
  state.driveId = root.driveId || null;
  state.displayName = root.displayName || root.name;
  state.hasResults = true;
  state.lastResultRoot = root;
  state.prevRoot = null;
  state.prevMeta = null;

  if (state.driveId) {
    if (opts.save) {
      // For comparison: the currently saved scan (before we overwrite it) is the "previous" one
      const prev = await window.api.loadScan(state.driveId);
      if (prev.ok) { state.prevRoot = prev.tree; state.prevMeta = prev.meta; }
      await window.api.saveScan({
        driveId: state.driveId, displayName: state.displayName,
        rootPath: root.path, totalSize: root.size,
        scannedAt: root.scannedAt || new Date().toISOString(), tree: root
      });
      state.scans = await window.api.listScans();
    } else {
      const prev = await window.api.loadPrevScan(state.driveId);
      if (prev && prev.ok) { state.prevRoot = prev.tree; state.prevMeta = prev.meta; }
    }
  }

  el.tabChanges.hidden = !state.prevRoot;
  el.scanMeta.textContent = root.scannedAt ? t('scannedMeta', { when: relativeTime(root.scannedAt) }) : '';
  renderVolumeStrip();
  // Refresh drive capacity/free-space in the background, then re-render the strip
  window.api.listDrives().then((drives) => {
    if (drives && drives.length) { state.drives = drives; renderVolumeStrip(); }
  }).catch(() => {});
  showView('results');
  setMode('browse');
}

// ---------- Tabs / modes ----------
function setMode(mode) {
  if (mode === 'changes' && !state.prevRoot) mode = 'browse';
  state.viewMode = mode;
  el.tabs.forEach((tb) => tb.classList.toggle('active', tb.dataset.mode === mode));
  el.modeBrowse.hidden = mode !== 'browse';
  el.modeFlat.hidden = mode === 'browse';
  if (mode === 'browse') renderCurrent();
  else if (mode === 'biggest') renderBiggest();
  else if (mode === 'changes') renderChanges();
}

// ---------- Browse mode ----------
function currentNode() { return state.navStack[state.navStack.length - 1]; }

function drillInto(node) {
  if (node.type !== 'dir' || !node.children || !node.children.length) return;
  state.navStack.push(node);
  renderCurrent();
}
function navigateTo(index) {
  state.navStack = state.navStack.slice(0, index + 1);
  renderCurrent();
}

function applySortFilter(children) {
  const minBytes = state.minSizeGB * GB;
  let out = children.slice();
  if (minBytes > 0) out = out.filter((c) => c.size >= minBytes);
  if (state.sortMode === 'size-asc') out.sort((a, b) => a.size - b.size);
  else if (state.sortMode === 'name-asc') out.sort((a, b) => a.name.localeCompare(b.name, window.I18N.lang));
  else out.sort((a, b) => b.size - a.size);
  return out;
}

function renderCurrent() {
  const node = currentNode();

  el.breadcrumb.innerHTML = '';
  state.navStack.forEach((n, i) => {
    if (i > 0) {
      const sep = document.createElement('span');
      sep.className = 'crumb-sep';
      sep.textContent = '‹';
      el.breadcrumb.appendChild(sep);
    }
    const crumb = document.createElement('span');
    const isCurrent = i === state.navStack.length - 1;
    crumb.className = 'crumb' + (isCurrent ? ' current' : '');
    crumb.textContent = i === 0 ? rootLabel(n) : dispName(n);
    if (!isCurrent) crumb.addEventListener('click', () => navigateTo(i));
    el.breadcrumb.appendChild(crumb);
  });

  el.currentName.textContent = node === state.scanRoot ? rootLabel(node) : dispName(node);
  el.currentSize.textContent = t('totalSize', { size: formatSize(node.size) });

  const children = applySortFilter(node.children || []);

  window.Treemap.render(el.treemap, children, {
    formatSize,
    highlightBytes: thresholdBytes(),
    onClick: (item) => drillInto(item),
    nameFor: dispName,
    emptyText: t('noDataDisplay')
  });

  renderList(children, node.size);
}

function renderList(children, totalSize) {
  el.itemsList.innerHTML = '';
  if (!children.length) {
    el.itemsList.innerHTML = '<div class="empty-state">' + t('noItems') + '</div>';
    return;
  }
  const thBytes = thresholdBytes();

  children.forEach((item) => {
    const pct = totalSize > 0 ? (item.size / totalSize) * 100 : 0;
    const isDir = item.type === 'dir';
    const isHighlight = isDir && item.size >= thBytes;
    const canDrill = isDir && item.children && item.children.length > 0;

    const row = document.createElement('div');
    row.className = 'item-row' + (canDrill ? ' clickable' : '') + (isHighlight ? ' highlight' : '');

    const nameCell = document.createElement('div');
    nameCell.className = 'item-name';
    const icon = document.createElement('span');
    icon.className = 'item-icon';
    icon.textContent = window.Treemap.iconFor(item.type);
    const nameText = document.createElement('span');
    nameText.className = 'item-name-text';
    nameText.textContent = dispName(item);
    nameCell.appendChild(icon);
    nameCell.appendChild(nameText);

    const sizeCell = document.createElement('div');
    sizeCell.className = 'item-size';
    sizeCell.textContent = formatSize(item.size);

    const pctCell = document.createElement('div');
    pctCell.className = 'item-pct-wrap';
    pctCell.innerHTML =
      '<div class="item-pct-bar"><div class="item-pct-fill ' +
      (isHighlight ? 'highlight' : '') + '" style="width:' + pct.toFixed(1) + '%"></div></div>' +
      '<span class="item-pct-text">' + pct.toFixed(1) + '%</span>';

    const actCell = document.createElement('div');
    actCell.className = 'item-actions';
    if (item.type !== 'more-bucket' && item.path) {
      actCell.appendChild(makeOpenBtn(item.path));
    }

    if (canDrill) row.addEventListener('click', () => drillInto(item));

    row.appendChild(nameCell);
    row.appendChild(sizeCell);
    row.appendChild(pctCell);
    row.appendChild(actCell);
    el.itemsList.appendChild(row);
  });
}

function makeOpenBtn(targetPath) {
  const btn = document.createElement('button');
  btn.className = 'btn btn-sm btn-ghost';
  btn.textContent = t('openExplorer');
  btn.title = t('openExplorerTitle');
  btn.addEventListener('click', (e) => {
    e.stopPropagation();
    openInExplorer(targetPath);
  });
  return btn;
}

// ---------- Flatten / navigation helpers ----------
function flattenDirs(root) {
  const out = [];
  (function walk(n) {
    out.push(n);
    for (const c of (n.children || [])) if (c.type === 'dir') walk(c);
  })(root);
  return out;
}

function findPathTo(root, target) {
  const tKey = String(target).toLowerCase();
  const stack = [root];
  let node = root;
  if (String(node.path).toLowerCase() === tKey) return stack;
  while (true) {
    let next = null;
    for (const c of (node.children || [])) {
      if (c.type !== 'dir') continue;
      const cp = String(c.path).toLowerCase();
      if (cp === tKey) { stack.push(c); return stack; }
      if (tKey.startsWith(cp + '\\')) { next = c; break; }
    }
    if (!next) return null;
    stack.push(next);
    node = next;
  }
}

function jumpTo(targetPath) {
  const stack = findPathTo(state.scanRoot, targetPath);
  if (!stack) { toast(t('folderNotFound')); return; }
  state.navStack = stack;
  setMode('browse');
}

// ---------- Biggest folders (flat) ----------
function renderBiggest() {
  el.flatTitle.textContent = t('biggestIn', { x: rootLabel(state.scanRoot) });
  el.flatHint.textContent = t('biggestHint');
  el.flatListHead.innerHTML =
    '<span>' + t('colFolder') + '</span><span>' + t('colSize') + '</span><span>' +
    t('colPctOfDrive') + '</span><span></span>';

  const rootSize = state.scanRoot.size || 1;
  const dirs = flattenDirs(state.scanRoot).filter((n) => n !== state.scanRoot && n.size > 0);
  dirs.sort((a, b) => b.size - a.size);
  const top = dirs.slice(0, 40);

  el.flatList.innerHTML = '';
  if (!top.length) { el.flatList.innerHTML = '<div class="empty-state">' + t('noData') + '</div>'; return; }

  top.forEach((n) => {
    const pct = (n.size / rootSize) * 100;
    const row = document.createElement('div');
    row.className = 'flat-row';

    const pathCell = document.createElement('div');
    pathCell.className = 'flat-path';
    const name = document.createElement('div');
    name.className = 'fp-name';
    name.textContent = '📁 ' + dispName(n);
    const dir = document.createElement('div');
    dir.className = 'fp-dir';
    dir.textContent = n.path;
    pathCell.appendChild(name);
    pathCell.appendChild(dir);

    const sizeCell = document.createElement('div');
    sizeCell.className = 'flat-size';
    sizeCell.textContent = formatSize(n.size);

    const pctCell = document.createElement('div');
    pctCell.textContent = pct.toFixed(1) + '%';

    const actCell = document.createElement('div');
    actCell.className = 'item-actions';
    if (n.path) actCell.appendChild(makeOpenBtn(n.path));

    row.addEventListener('click', () => jumpTo(n.path));
    row.appendChild(pathCell);
    row.appendChild(sizeCell);
    row.appendChild(pctCell);
    row.appendChild(actCell);
    el.flatList.appendChild(row);
  });
}

// ---------- Changes vs previous scan ----------
function renderChanges() {
  el.flatTitle.textContent = t('changesTitle');
  el.flatHint.textContent = state.prevMeta
    ? t('changesHint', { when: relativeTime(state.prevMeta.scannedAt) })
    : '';
  el.flatListHead.innerHTML =
    '<span>' + t('colFolder') + '</span><span>' + t('colCurrentSize') + '</span><span>' +
    t('colChange') + '</span><span></span>';

  const MIN_DELTA = 50 * 1024 * 1024;
  const prevMap = new Map();
  for (const n of flattenDirs(state.prevRoot)) prevMap.set(String(n.path).toLowerCase(), n);

  const changes = [];
  const seen = new Set();
  for (const n of flattenDirs(state.scanRoot)) {
    if (n === state.scanRoot) continue; // skip the drive root itself
    const key = String(n.path).toLowerCase();
    seen.add(key);
    const prevNode = prevMap.get(key);
    const delta = n.size - (prevNode ? prevNode.size : 0);
    if (Math.abs(delta) < MIN_DELTA) continue;
    changes.push({ node: n, delta, isNew: prevNode === undefined, exists: true });
  }
  // Folders that were deleted (existed before, gone now) → freed space
  const rootKey = String(state.scanRoot.path).toLowerCase();
  for (const [key, pnode] of prevMap) {
    if (key === rootKey) continue;
    if (!seen.has(key) && pnode.size >= MIN_DELTA) {
      changes.push({ node: { name: pnode.name, path: pnode.path, size: 0 }, delta: -pnode.size, removed: true, exists: false });
    }
  }

  changes.sort((a, b) => b.delta - a.delta);
  const top = changes.slice(0, 60);

  el.flatList.innerHTML = '';
  if (!top.length) {
    el.flatList.innerHTML = '<div class="empty-state">' + t('noData') + '</div>';
    return;
  }

  top.forEach((ch) => {
    const n = ch.node;
    const row = document.createElement('div');
    row.className = 'flat-row';

    const pathCell = document.createElement('div');
    pathCell.className = 'flat-path';
    const name = document.createElement('div');
    name.className = 'fp-name';
    name.textContent = (ch.removed ? '🗑️ ' : '📁 ') + dispName(n);
    const dir = document.createElement('div');
    dir.className = 'fp-dir';
    dir.textContent = n.path;
    pathCell.appendChild(name);
    pathCell.appendChild(dir);

    const sizeCell = document.createElement('div');
    sizeCell.className = 'flat-size';
    sizeCell.textContent = ch.removed ? '-' : formatSize(n.size);

    const deltaCell = document.createElement('div');
    deltaCell.className = 'flat-size ' +
      (ch.isNew ? 'delta-new' : ch.delta > 0 ? 'delta-up' : 'delta-down');
    deltaCell.textContent = ch.isNew ? t('newPlus', { size: formatSize(ch.delta) })
      : (ch.delta > 0 ? '▲ +' : '▼ −') + formatSize(Math.abs(ch.delta));

    const actCell = document.createElement('div');
    actCell.className = 'item-actions';
    if (ch.exists && n.path) actCell.appendChild(makeOpenBtn(n.path));

    if (ch.exists) row.addEventListener('click', () => jumpTo(n.path));
    else row.style.cursor = 'default';

    row.appendChild(pathCell);
    row.appendChild(sizeCell);
    row.appendChild(deltaCell);
    row.appendChild(actCell);
    el.flatList.appendChild(row);
  });
}

async function openInExplorer(targetPath) {
  const res = await window.api.openInExplorer(targetPath);
  if (!res.ok) toast(t('cantOpen'));
}

// ---------- Progress listener ----------
window.api.onScanProgress((data) => {
  if (!data) return;
  if (data.phase === 'parse') {
    el.scanCount.textContent = t('processing');
  } else if (typeof data.filesScanned === 'number') {
    el.scanCount.textContent = t('filesScanned', { n: fmtInt(data.filesScanned) });
  }
  if (data.currentPath) el.scanPath.textContent = data.currentPath;
  else if (data.phase === 'done') el.scanPath.textContent = '';
});

// ---------- Language ----------
function updateLangToggle() {
  el.langToggle.textContent = t('langToggle');
}

window.onLanguageChanged = function (lang) {
  updateLangToggle();
  // Tell the main process so the tray menu follows the UI language
  if (window.api.setLanguage) window.api.setLanguage(lang);
  // Re-render everything dynamic in the new language
  renderDrives();
  renderVolumeStrip();
  if (state.scanRoot) {
    el.scanMeta.textContent = state.scanRoot.scannedAt
      ? t('scannedMeta', { when: relativeTime(state.scanRoot.scannedAt) }) : '';
  }
  if (!el.viewResults.hidden) setMode(state.viewMode || 'browse');
  if (!el.aboutModal.hidden) renderWhatsNew();
};

el.langToggle.addEventListener('click', () => {
  window.I18N.setLang(window.I18N.lang === 'he' ? 'en' : 'he');
});

// ---------- Event wiring ----------
el.btnHome.addEventListener('click', goHome);
el.btnBackResults.addEventListener('click', () => {
  if (!state.hasResults) return;
  showView('results');
  setMode(state.viewMode || 'browse');
});
el.btnRefresh.addEventListener('click', loadDrives);
el.btnCancelScan.addEventListener('click', cancelScan);

el.tabs.forEach((tb) => tb.addEventListener('click', () => setMode(tb.dataset.mode)));

el.sortSelect.addEventListener('change', (e) => {
  state.sortMode = e.target.value;
  if (state.viewMode === 'browse') renderCurrent();
});
el.minsizeSlider.addEventListener('input', (e) => {
  state.minSizeGB = Number(e.target.value);
  el.minsizeValue.textContent = state.minSizeGB;
  if (state.viewMode === 'browse') renderCurrent();
});
el.thresholdSlider.addEventListener('input', (e) => {
  state.thresholdGB = Number(e.target.value);
  el.thresholdValue.textContent = state.thresholdGB;
  if (state.viewMode === 'browse') renderCurrent();
});

let resizeTimer = null;
window.addEventListener('resize', () => {
  clearTimeout(resizeTimer);
  resizeTimer = setTimeout(() => {
    if (!el.viewResults.hidden && state.viewMode === 'browse') renderCurrent();
  }, 150);
});

// ---------- Version & updates ----------
// Friendly, non-technical release notes - one entry per version, per language.
const RELEASE_NOTES = [
  {
    v: '1.3.1', date: '26.7.2026',
    en: 'Text polish everywhere: cleaner punctuation and wording across the app, the tooltips, and the website.',
    he: 'ליטוש טקסטים בכל מקום: פיסוק וניסוח נקיים יותר באפליקציה, בחלוניות המידע ובאתר.'
  },
  {
    v: '1.3.0', date: '26.7.2026',
    en: 'The app now speaks English too - switch language any time with the button in the header. Plus, the drive capacity bar (used / free with a percentage) now stays visible while you browse inside the drive, not just on the home screen.',
    he: 'האפליקציה מדברת עכשיו גם אנגלית - מחליפים שפה בלחיצה על הכפתור בכותרת. בנוסף, פס הקיבולת של הכונן (בשימוש / פנוי עם אחוזים) מוצג עכשיו גם בזמן העיון בתוך הכונן, לא רק במסך הבית.'
  },
  {
    v: '1.2.1', date: '22.7.2026',
    en: 'Added an "About & what\'s new" screen (the one you\'re looking at!) showing the version and the change list for every update. Also fixed an update banner that appeared empty.',
    he: 'נוסף מסך "אודות ומה חדש" (זה שאתה רואה עכשיו!) שבו רואים את הגרסה ואת רשימת השינויים בכל עדכון. בנוסף תוקן באנר עדכון שהופיע ריק.'
  },
  {
    v: '1.2.0', date: '22.7.2026',
    en: 'You can now see the version number and update with one click from inside the app. Added a small tray icon next to the clock for quick open/close, and fixed the filter sliders that worked backwards.',
    he: 'עכשיו רואים את מספר הגרסה ואפשר להתעדכן בלחיצה מתוך האפליקציה. נוסף אייקון קטן ליד השעון לפתיחה וסגירה מהירה, ותוקנו מחווני הסינון שעבדו הפוך.'
  },
  {
    v: '1.1.0', date: '22.7.2026',
    en: 'Two new screens: "Biggest folders" that immediately shows the space hogs, and "Changes" that compares against the previous scan. Scans can now be saved and revisited, and we got a new icon.',
    he: 'נוספו שני מסכים: "התיקיות הכי גדולות" שמראה מיד את זללני המקום, ו"שינויים" שמשווה לסריקה הקודמת. אפשר גם לשמור סריקות ולחזור אליהן, וקיבלנו אייקון חדש.'
  },
  {
    v: '1.0.0', date: '22.7.2026',
    en: 'The first release 🎉 - fast drive scanning with a colorful treemap and an "Open in Explorer" button to delete what you don\'t need.',
    he: 'ההשקה הראשונה 🎉 - סריקת כוננים מהירה עם מפת ריבועים צבעונית וכפתור "פתח בסייר" כדי למחוק מה שלא צריך.'
  }
];

const updateState = { pendingVersion: null, currentVersion: '' };

async function initVersion() {
  try {
    const v = await window.api.getVersion();
    updateState.currentVersion = v;
    el.versionPill.textContent = 'v' + v + ' ⓘ';
    el.aboutCurrentVersion.textContent = 'v' + v;
    // One-time "what's new" popup after a version update
    let seen = null;
    try { seen = localStorage.getItem('lastSeenVersion'); } catch (_) {}
    if (seen && seen !== v) openAbout();
    try { localStorage.setItem('lastSeenVersion', v); } catch (_) {}
  } catch (_) { el.versionPill.textContent = ''; }
}

function renderWhatsNew() {
  el.whatsnewList.innerHTML = '';
  const lang = window.I18N.lang;
  RELEASE_NOTES.forEach((r) => {
    const item = document.createElement('div');
    item.className = 'wn-item' + (r.v === updateState.currentVersion ? ' latest' : '');
    const head = document.createElement('div');
    head.className = 'wn-head';
    const ver = document.createElement('span');
    ver.className = 'wn-ver';
    ver.textContent = 'v' + r.v;
    head.appendChild(ver);
    if (r.v === updateState.currentVersion) {
      const nb = document.createElement('span');
      nb.className = 'wn-badge-new';
      nb.textContent = t('yourVersion');
      head.appendChild(nb);
    }
    const date = document.createElement('span');
    date.className = 'wn-date';
    date.textContent = r.date;
    head.appendChild(date);
    const text = document.createElement('div');
    text.className = 'wn-text';
    text.textContent = r[lang] || r.en;
    item.appendChild(head);
    item.appendChild(text);
    el.whatsnewList.appendChild(item);
  });
}

function openAbout() {
  renderWhatsNew();
  el.aboutUpdateStatus.textContent = '';
  el.aboutModal.hidden = false;
}
function closeAbout() { el.aboutModal.hidden = true; }

function showUpdateBanner(text, actionLabel, actionFn) {
  el.updateText.textContent = text;
  if (actionLabel) {
    el.updateAction.textContent = actionLabel;
    el.updateAction.hidden = false;
    el.updateAction.onclick = actionFn;
  } else {
    el.updateAction.hidden = true;
    el.updateAction.onclick = null;
  }
  el.updateBanner.hidden = false;
}

el.versionPill.addEventListener('click', openAbout);
el.aboutClose.addEventListener('click', closeAbout);
el.aboutModal.addEventListener('click', (e) => { if (e.target === el.aboutModal) closeAbout(); });
document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && !el.aboutModal.hidden) closeAbout(); });

el.aboutCheck.addEventListener('click', async () => {
  el.aboutUpdateStatus.textContent = t('checking');
  const res = await window.api.checkForUpdates();
  if (res && res.dev) el.aboutUpdateStatus.textContent = t('devOnly');
});

el.updateDismiss.addEventListener('click', () => { el.updateBanner.hidden = true; });

window.api.onUpdateStatus((data) => {
  if (!data) return;
  switch (data.status) {
    case 'checking':
      el.aboutUpdateStatus.textContent = t('checking');
      break;
    case 'available':
      updateState.pendingVersion = data.version;
      el.versionPill.classList.add('has-update');
      el.aboutUpdateStatus.textContent = t('vAvailable', { v: data.version });
      showUpdateBanner(t('updAvailable', { v: data.version }), t('updDownload'), async () => {
        showUpdateBanner(t('updDownloading', { p: 0 }), null, null);
        await window.api.downloadUpdate();
      });
      break;
    case 'none':
      el.aboutUpdateStatus.textContent = t('upToDate');
      break;
    case 'progress':
      el.aboutUpdateStatus.textContent = t('updDownloading', { p: data.percent });
      showUpdateBanner(t('updDownloading', { p: data.percent }), null, null);
      break;
    case 'downloaded':
      el.aboutUpdateStatus.textContent = t('updReady', { v: data.version });
      showUpdateBanner(t('updReady', { v: data.version }), t('updInstall'), () => {
        window.api.installUpdate();
      });
      break;
    case 'error':
      // Silent - don't bother the user about a failed automatic check
      break;
  }
});

// ---------- Init ----------
window.I18N.apply();
updateLangToggle();
if (window.api.setLanguage) window.api.setLanguage(window.I18N.lang);
initVersion();
loadDrives();
